/*
*	Pinlayout is defined here.
*	-- layout for Atmega2560/Mega
*/

#define MOTOR_FRONT_LEFT_PWM	4	// DIGITAL
#define MOTOR_FRONT_LEFT_A		23	// DIGITAL
#define MOTOR_FRONT_LEFT_B		25	// DIGITAL

#define MOTOR_FRONT_RIGHT_PWM	5	// DIGITAL
#define MOTOR_FRONT_RIGHT_A		27	// DIGITAL
#define MOTOR_FRONT_RIGHT_B		29	// DIGITAL

#define MOTOR_BACK_LEFT_PWM		6	// DIGITAL
#define MOTOR_BACK_LEFT_A		31	// DIGITAL
#define MOTOR_BACK_LEFT_B		33	// DIGITAL

#define MOTOR_BACK_RIGHT_PWM	7	// DIGITAL
#define MOTOR_BACK_RIGHT_A		35	// DIGITAL
#define MOTOR_BACK_RIGHT_B		37	// DIGITAL

#define HALL_FRONT_LEFT			18	// DIGITAL
#define HALL_FRONT_RIGHT		19	// DIGITAL
#define HALL_BACK_LEFT			2	// DIGITAL
#define HALL_BACK_RIGHT			3	// DIGITAL

#define IMU_SDA					20	// DIGITAL
#define IMU_SCL					21	// DIGITAL

#define GPS_TX					16	// DIGITAL
#define GPS_RX					17	// DIGITAL

#define CURRENT_FRONT_LEFT		0	// ANALOG
#define CURRENT_FRONT_RIGHT		1	// ANALOG
#define CURRENT_BACK_LEFT		2	// ANALOG
#define CURRENT_BACK_RIGHT		3	// ANALOG

#define SONAR_FRONT_LEFT		4	// ANALOG
#define SONAR_FRONT_RIGHT		5	// ANALOG
#define SONAR_BACK_LEFT			6	// ANALOG
#define SONAR_BACK_RIGHT		7	// ANALOG

#define RELAY_POWER				48	// DIGITAL
#define RELAY_FAN				46	// DIGITAL
#define RELAY_V12				44	// DIGITAL
#define RELAY_MOTORS			42	// DIGITAL
