compile:
  libraries: ~
  platforms:
    - mega2560

unittest:
  libraries: ~
  platforms:
    - mega2560

platforms:
  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - __AVR__
        - __AVR_ATmega2560__
        - ARDUINO_ARCH_AVR
        - ARDUINO_AVR_MEGA2560
        - ARDUINO_CI
      warnings:
      flags:
